title: staging.der-mow.de
author:
  name: dermow
  email: s.seibold@posteo.de

show_excerpts: true # set to true to show excerpts on the homepage
excerpt_separator: <!-- excerpt-end -->
google_analytics: false

disqus:
  shortname: der-mow
  url: https://staging.der-mow.de

minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: jekyllrb
    github: jekyll

# Build settings
theme: jekyll-theme-minimal

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

paginate: 20
paginate_path: /page:num
